using Asterion.Core;
using System.Text.Json;
using System.Xml;

int passed=0; List<string> failed=[];
void Test(string name,Action test){try{test();Console.WriteLine("PASS "+name);passed++;}catch(Exception e){Console.WriteLine("FAIL "+name+": "+e.Message);failed.Add(name);}}
void Assert(bool condition,string reason="Assertion failed"){if(!condition)throw new Exception(reason);}
Test("Bindings: player wrapper, keyboard, unsupported device and explicit unbind",()=>{
 var b=Bindings.Parse("<ActionMaps><ActionProfiles><actionmap name='player'><action name='inventory'><rebind input='kb1_tab'/></action><action name='foo'><rebind input='js1_button1'/></action><action name='bar'><rebind input=''/></action></actionmap></ActionProfiles></ActionMaps>");
 Assert(b.Count==3&&b[0].Status=="BOUND"&&b[1].Status=="UNSUPPORTED INPUT"&&b[2].Status=="UNBOUND");});
Test("Bindings: exported profile and modifier chord",()=>{var b=Bindings.Parse("<ActionMaps><actionmap name='spaceship'><action name='gear'><rebind input='kb1_lalt+n'/></action></actionmap></ActionMaps>");Assert(b.Single().Status=="BOUND");Assert(KeyChord.TryParse(b[0].Input,out var k)&&k.ScanCodes.SequenceEqual(new ushort[]{56,49}));});
Test("Bindings: never guess unsupported input",()=>{foreach(var input in new[]{"n","kb1_mouse1","js1_button2","kb1_lalt+unknown","kb1_n+n","kb1_"})Assert(!KeyChord.TryParse(input,out _));});
Test("Bindings: reject XML external entities",()=>{try{Bindings.Parse("<!DOCTYPE foo [<!ENTITY xxe SYSTEM 'file:///secret'>]><ActionMaps>&xxe;</ActionMaps>");throw new Exception("DTD accepted");}catch(XmlException){}});
Test("Bindings: reject complex activation",()=>Assert(Bindings.Parse("<ActionMaps><actionmap name='x'><action name='y'><rebind input='kb1_n' multiTap='2'/></action></actionmap></ActionMaps>").Single().Status=="UNSUPPORTED ACTIVATION"));
Test("Input: extended keys and mouse side buttons",()=>{Assert(KeyChord.TryParse("kb1_rctrl+up",out var k)&&k.ScanCodes[1]==0x148);Assert(KeyChord.TryParse("kb1_mouse4",out k)&&k.MouseButton==1);});
Test("Game.log: client spawn defaults to on-foot",()=>Assert(GameLog.Parse("<2026-09-09T01:24:02.349Z> [CSessionManager::OnClientSpawned] Spawned!")?.Context==Context.ON_FOOT));
Test("Game.log: mission and reward events",()=>{var a=GameLog.Parse("<SHUDEvent_OnNotification> \"Contract Accepted:  Medium Cargo Haul\" MissionId:[abc]");Assert(a?.Kind=="mission_accepted"&&a.Mission=="Medium Cargo Haul");var r=GameLog.Parse("<SHUDEvent_OnNotification> Awarded 12,500 aUEC");Assert(r?.Kind=="award"&&r.Amount==12500);Assert(GameLog.Parse("<EndMission> MissionId[abc] CompletionType[Complete] Reason[Mission Ended]")?.Kind=="mission_complete");});
Test("Game.log: ignore another vehicle and unstructured text",()=>{Assert(GameLog.Parse("NPC entered RSI_Constellation") is null);Assert(GameLog.Parse("LandingArea current vehicle stowed") is null);});
Test("Game.log: session events from observed signatures",()=>{Assert(GameLog.Parse("[Notice] <Join PU> address[redacted]")?.Kind=="session");Assert(GameLog.Parse("[Notice] <SystemQuit> CSystem::Quit")?.Context==Context.UNKNOWN);});
Test("Game.log: shard and initial location from Join PU",()=>{var e=GameLog.Parse("<Join PU> address[1.2.3.4] port[64090] shard[pub_euw1_123_456] locationId[Stanton4_Orison]");Assert(e?.Shard=="pub_euw1_123_456");Assert(e?.Location=="Stanton4_Orison");var u=GameLog.Parse("<Update Shard Id> New Shard Id: pub_euw1_999_111. Old Shard Id [x]");Assert(u?.Shard=="pub_euw1_999_111");});
Test("Game.log: observed trade cash-flow",()=>{var b=GameLog.Parse("<2026-09-20T00:00:00.000Z> <CEntityComponentCommodityUIProvider::SendCommodityBuyRequest> shopName[Admin] price[12500.000000] resourceGUID[12345678-abcd] quantity[100 cSCU]");Assert(b?.Kind=="trade_buy"&&b.Amount==-12500);var s=GameLog.Parse("<2026-09-20T00:00:01.000Z> <CEntityComponentCommodityUIProvider::SendCommoditySellRequest> shopName[TDD] amount[18000.000000] resourceGUID[12345678-abcd] quantity[1]");Assert(s?.Kind=="trade_sell"&&s.Amount==18000);});
Test("Game.log: custom adapter requires local actor",()=>{var rules=new[]{new LogRule("SeatEntered", "actor=LOCAL",Context.FLIGHT,"RSI Test")};Assert(GameLog.Parse("SeatEntered actor=OTHER",rules)==null);Assert(GameLog.Parse("SeatEntered actor=LOCAL",rules)?.Ship=="RSI Test");});
Test("Game.log: invalid regex contained",()=>Assert(GameLog.Parse("local",[new("[","local",Context.FLIGHT)])==null));
Test("Context: manual override wins; AUTO resumes observed context",()=>{var m=new ContextMachine();m.Apply(new("x","",Context.FLIGHT));m.Force(Context.ON_FOOT);Assert(m.Current==Context.ON_FOOT);m.Force(null);Assert(m.Current==Context.FLIGHT);m.Reset();Assert(m.Current==Context.UNKNOWN);});
Test("Safety: tap cannot commit dangerous action",()=>{long t=0;var gate=new HoldGate(()=>t);gate.Begin("a","eject");t=100;Assert(!gate.Commit("a","eject",1800));});
Test("Safety: heartbeat hold, single use and action identity",()=>{long t=0;var gate=new HoldGate(()=>t);gate.Begin("a","eject");for(int i=0;i<12;i++){t+=150;gate.Pulse("a");}Assert(gate.Commit("a","eject",1800));Assert(!gate.Commit("a","eject",1800));gate.Begin("a","eject");t+=1800;Assert(!gate.Commit("a","power",1800));});
Test("Safety: no pulse / stalled pulse / cancel cannot commit",()=>{long t=0;var g=new HoldGate(()=>t);g.Begin("a","x");t=1800;Assert(!g.Commit("a","x",1800));g.Begin("a","x");t+=700;g.Pulse("a");Assert(!g.Commit("a","x",1800));g.Begin("a","x");g.Cancel("a");Assert(!g.Commit("a","x",1800));});
Test("Tail: initial history ignored, partial append combined, truncate recovered",()=>{
 string dir=Path.Combine(Path.GetTempPath(),"asterion-test-"+Guid.NewGuid());Directory.CreateDirectory(dir);string p=Path.Combine(dir,"Game.log");
 try{File.WriteAllText(p,"old\n");using var tail=new LogTail();tail.SetPath(p);Assert(!tail.Read(true).Any());File.AppendAllText(p,"new");Assert(!tail.Read(true).Any());File.AppendAllText(p," event\n");Assert(tail.Read(true).Single()=="new event");File.WriteAllText(p,"x\n");Assert(tail.Read(true).Single()=="x");}finally{Directory.Delete(dir,true);}});
Test("Tail: empty file followed by UTF-8 split writes",()=>{
 string dir=Path.Combine(Path.GetTempPath(),"asterion-test-"+Guid.NewGuid());Directory.CreateDirectory(dir);string p=Path.Combine(dir,"Game.log");
 try{File.WriteAllBytes(p,[]);using var tail=new LogTail();tail.SetPath(p);tail.Read(true);using(var f=new FileStream(p,FileMode.Append)){f.WriteByte(0xc3);}Assert(!tail.Read(true).Any());using(var f=new FileStream(p,FileMode.Append)){f.Write(new byte[]{0xa9,10});}Assert(tail.Read(true).Single()=="é");}finally{Directory.Delete(dir,true);}});
if(args.Length>0)Test("Catalog: unique IDs, required pages, guarded risky actions",()=>{using var j=JsonDocument.Parse(File.ReadAllText(args[0]));var actions=j.RootElement.GetProperty("actions").EnumerateArray().ToArray();Assert(actions.Select(a=>a.GetProperty("id").GetString()).Distinct().Count()==actions.Length);foreach(string id in new[]{"power","eject","destruct"})Assert(actions.Single(a=>a.GetProperty("id").GetString()==id).GetProperty("dangerous").GetBoolean());foreach(string page in new[]{"Flight","Combat","FPS","Power","Targeting"})Assert(actions.Any(a=>a.GetProperty("page").GetString()==page));});
Test("Modifiers: game-style f6+lalt sends modifier first",()=>{Assert(KeyChord.TryParse("kb1_f6+lalt",out var chord));Assert(chord.ScanCodes.SequenceEqual(new ushort[]{56,64}));});
Test("Feedback: unknown toggle never invents an ON state",()=>{var f=new CommandFeedback();f.Sent("lights");Assert(f.Estimate("lights")==null&&f.Touched("lights"));});
Test("Feedback: calibrated toggle, explicit doors, reset",()=>{var f=new CommandFeedback();f.Calibrate("lights",false);f.Sent("lights");Assert(f.Estimate("lights")==true);f.Sent("lights");Assert(f.Estimate("lights")==false);f.Sent("doorsOpen");Assert(f.Estimate("doors")==true);f.Sent("doorsClose");Assert(f.Estimate("doors")==false);f.Reset();Assert(f.Estimate("lights")==null&&!f.Touched("doors"));});
Test("Power: adjustment counts are deltas, maximum invalidates them",()=>{var f=new CommandFeedback();f.Sent("weaponsUp");f.Sent("weaponsUp");f.Sent("weaponsDown");Assert(f.Delta("weapons")==1);f.Sent("weaponsMax");Assert(f.Delta("weapons")==0);f.Sent("shieldsDown");f.Sent("balance");Assert(f.Delta("shields")==0);});
Test("Context: observed local driver exit only",()=>{const string line="<Vehicle Control Flow> CVehicleMovementBase::ClearDriver: Local client node [12345] releasing control token for 'ORIG_Test_98765' [98765] [Team_CGP4][Vehicle]";Assert(GameLog.Parse(line)?.Context==Context.ON_FOOT);Assert(GameLog.Parse(line.Replace("Local client node","Remote client node"))==null);Assert(GameLog.Parse("<SCItemVehicleLandingGearSystem::OnEngineStateChange()> Failed to detach vehicle due to control token not being granted")==null);});
if(args.Length>0)Test("Catalog: current energy actions and distinct door commands",()=>{using var j=JsonDocument.Parse(File.ReadAllText(args[0]));var a=j.RootElement.GetProperty("actions").EnumerateArray().ToDictionary(x=>x.GetProperty("id").GetString()!);Assert(a["doors"].GetProperty("action").GetString()=="v_toggle_all_doors");Assert(a["doorunlock"].GetProperty("action").GetString()=="v_unlock_all_doors");Assert(a["eject"].GetProperty("map").GetString()=="seat_general");Assert(a["destruct"].GetProperty("pressMs").GetInt32()>=600);foreach(var id in new[]{"weaponsUp","enginesUp","shieldsUp"})Assert(a[id].GetProperty("action").GetString()!.StartsWith("v_engineering_assignment_"));});
Console.WriteLine($"{passed} passed, {failed.Count} failed");return failed.Count==0?0:1;
