// Run against a companion started with --simulate --data <test folder>.
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const cfg=JSON.parse(fs.readFileSync(process.env.ASTERION_TEST_CONFIG));const base=`http://127.0.0.1:${cfg.port}`;
async function client(){const ws=new WebSocket(base.replace('http:','ws:')+'/events');const messages=[];ws.onmessage=e=>messages.push(JSON.parse(e.data));await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});try{const first=await until(()=>messages.find(m=>m.type==='state'));assert.equal(first.state.simulation,true,'Tests require the dedicated simulation instance');}catch(e){ws.close();throw e;}return {ws,messages};}
async function until(fn,ms=4500){const end=Date.now()+ms;while(Date.now()<end){const v=fn();if(v)return v;await new Promise(r=>setTimeout(r,25));}throw Error('Timeout');}
test('HTTP health and state use automatic loopback link',async()=>{const h=await(await fetch(base+'/health')).json();assert.equal(h.protocol,2);assert.equal(h.autoLink,true);const r=await fetch(base+'/state');assert.equal(r.status,200);const s=await r.json();assert.equal(s.protocol,2);assert.equal(s.simulation,true);});
test('state event; manual context; POC Windows signal',async()=>{const c=await client();try{for(const [type,id] of [['context','FLIGHT'],['test','']]){c.ws.send(JSON.stringify({type,id,requestId:type}));await until(()=>c.messages.find(m=>m.requestId===type));assert.equal(c.messages.find(m=>m.requestId===type).ok,true);}const state=await(await fetch(base+'/state')).json();assert.equal(state.context,'FLIGHT');assert(state.feed.some(e=>e.text.includes('Windows companion received test signal')));}finally{c.ws.close();}});
test('unknown action; direct dangerous action refused',async()=>{const c=await client();try{for(const id of ['not-real','eject']){c.ws.send(JSON.stringify({type:'action',id,requestId:id}));await until(()=>c.messages.find(m=>m.requestId===id));assert.equal(c.messages.find(m=>m.requestId===id).ok,false);await new Promise(r=>setTimeout(r,220));}}finally{c.ws.close();}});
test('server validates continuous hold and rejects replay',async()=>{const c=await client();try{c.ws.send(JSON.stringify({type:'holdBegin',id:'eject'}));const t=setInterval(()=>c.ws.send(JSON.stringify({type:'holdPulse'})),150);await new Promise(r=>setTimeout(r,cfg.holdDuration+120));clearInterval(t);c.ws.send(JSON.stringify({type:'action',id:'eject',requestId:'good'}));await until(()=>c.messages.find(m=>m.requestId==='good'));assert.equal(c.messages.find(m=>m.requestId==='good').ok,true);await new Promise(r=>setTimeout(r,230));c.ws.send(JSON.stringify({type:'action',id:'eject',requestId:'replay'}));await until(()=>c.messages.find(m=>m.requestId==='replay'));assert.equal(c.messages.find(m=>m.requestId==='replay').ok,false);}finally{c.ws.close();}});

test('appearance settings are persisted through the protocol',async()=>{const c=await client();try{for(const [type,id] of [['accent2','#ff8800'],['background','#101820'],['panel','#182430'],['panelOpacity','88'],['fontScale','105'],['radius','12'],['glow','40'],['quickColumns','9'],['density','compact'],['animations','0']]){const key='appearance-'+type;c.ws.send(JSON.stringify({type,id,requestId:key}));await until(()=>c.messages.find(m=>m.requestId===key));assert.equal(c.messages.find(m=>m.requestId===key).ok,true);}const s=await(await fetch(base+'/state')).json();assert.equal(s.appearance.accent2,'#FF8800');assert.equal(s.appearance.panelOpacity,88);assert.equal(s.appearance.fontScale,105);assert.equal(s.appearance.radius,12);assert.equal(s.appearance.quickColumns,9);assert.equal(s.appearance.density,'compact');assert.equal(s.appearance.animations,false);}finally{c.ws.close();}});
test('HTTP cannot execute dangerous commands',async()=>{const r=await fetch(base+'/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:'destruct'})});assert.equal(r.status,409);});
