
'use strict';
(function(){
  const $=id=>document.getElementById(id);
  const VERSION='0.3.0', DEV='DEV.3', PORT=32147;
  const labels={power:'Alimentation',weapons:'Armes',engines:'Moteurs',shields:'Boucliers',coolers:'Refroidisseurs',pw:'Priorité armes',pt:'Priorité moteurs',ps:'Priorité boucliers',balance:'Équilibrer énergie',master:'SCM / NAV',brake:'Frein spatial',gear:'Train',vtol:'VTOL',landing:'Demander ATC',autoland:'Atterrissage auto',decoupled:'Découplé',cruise:'Régulateur',gsafe:'G-Safe',esp:'ESP',limiter:'Limiteur',mfd:'MFD suivant',mobiglas:'mobiGlas',starmap:'Starmap',camera:'Caméra externe',ping:'Ping',scan:'Scan',lights:'Éclairage',headtrack:'Head tracking',doors:'Portes',lock:'Verrouiller cible',hostile:'Hostile suivant',friendly:'Allié suivant',attacker:'Attaquant suivant',subtarget:'Sous-composant',pin:'Épingler cible',decoy:'Leurre',noise:'Noise',missile:'Mode missile',arm:'Armer missile',sf:'Avant',sr:'Arrière',sl:'Gauche',sright:'Droite',stop:'Haut',sbottom:'Bas',sreset:'Reset',helmet:'Casque',flashlight:'Lampe',wipe:'Visière',inventory:'Inventaire',interact:'Interaction',heal:'Soin',salute:'Salut',wave:'Faire signe',respect:'Respect',eject:'Éjection',destruct:'Autodestruction'};
  const glyph={power:'PWR',weapons:'WPN',engines:'ENG',shields:'SHD',coolers:'CLR',master:'SCM',brake:'BRK',gear:'LG',vtol:'VT',landing:'ATC',autoland:'AUTO',decoupled:'DEC',cruise:'CRS',gsafe:'G',esp:'ESP',limiter:'LIM',mfd:'MFD',mobiglas:'MG',starmap:'MAP',camera:'CAM',ping:'PNG',scan:'SCN',lights:'LGT',headtrack:'HEAD',doors:'DR',lock:'TGT',hostile:'HST',friendly:'FRD',attacker:'ATK',subtarget:'SUB',pin:'PIN',decoy:'DCY',noise:'NS',missile:'MSL',arm:'ARM',sf:'F',sr:'R',sl:'L',sright:'R',stop:'UP',sbottom:'DN',sreset:'RST',helmet:'HLM',flashlight:'LMP',wipe:'VIS',inventory:'INV',interact:'USE',heal:'MED',salute:'HI',wave:'WAV',respect:'RSP',eject:'EJ',destruct:'SD'};
  let state=null,page='Home',ws=null,retry=null,connected=false,backoff=800,hold=null,ping=null,lastMessage=0;
  const pending=new Map();
  $('versionBadge').textContent='v'+VERSION+' · '+DEV;
  const toast=t=>$('toast').textContent=t;
  const esc=v=>String(v==null?'':v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const short=v=>(!v||v==='Unavailable')?'—':String(v).split('-')[0].slice(0,16);
  function raw(o){if(ws&&ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(o));}
  function send(type,id){
    if(!connected)return Promise.reject(new Error('Companion déconnecté'));
    const requestId=String(Date.now())+Math.random(); raw({type:type,id:id||'',requestId:requestId});
    return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{pending.delete(requestId);reject(new Error('Délai dépassé'));},4500);pending.set(requestId,{resolve,reject,timeout});});
  }
  function disconnect(){connected=false;cancelHold();clearInterval(ping);$('connection').textContent='DÉCONNECTÉ';$('game').textContent='ARRÊTÉ';for(const p of pending.values()){clearTimeout(p.timeout);p.reject(new Error('Déconnecté'));}pending.clear();render();}
  function connect(){
    clearTimeout(retry);if(ws){ws.onclose=null;try{ws.close();}catch(e){}}disconnect();$('connection').textContent='CONNEXION…';
    const s=new WebSocket('ws://127.0.0.1:'+PORT+'/events');ws=s;
    s.onopen=()=>lastMessage=Date.now();
    s.onmessage=e=>{if(s!==ws)return;lastMessage=Date.now();let m;try{m=JSON.parse(e.data);}catch(x){return;}
      if(m.type==='state'&&Number(m.state&&m.state.protocol)>=2){const first=!connected;connected=true;backoff=800;state=m.state;if(first){clearInterval(ping);ping=setInterval(()=>{if(Date.now()-lastMessage>12000)s.close();else raw({type:'ping'});},4000);}if(state.autoContext){if(state.context==='ON_FOOT')page='FPS';else if(page==='FPS')page='Home';}chrome();render();}
      if(m.type==='ack'){const p=pending.get(m.requestId);if(p){clearTimeout(p.timeout);pending.delete(m.requestId);m.ok?p.resolve(m):p.reject(new Error(m.error||'Commande refusée'));}}
    };
    s.onerror=()=>s.close();s.onclose=()=>{if(s!==ws)return;disconnect();retry=setTimeout(connect,backoff);backoff=Math.min(10000,Math.round(backoff*1.6));};
  }
  function chrome(){const a=state&&state.appearance||{},r=document.documentElement;r.style.setProperty('--accent',a.accent||state.accent||'#24d9e8');r.style.setProperty('--accent2',a.accent2||'#298cff');r.style.setProperty('--bg',a.background||'#040b11');r.style.setProperty('--panel',a.panel||'#0b1720');r.dataset.theme=a.theme||'nebula';$('connection').textContent='CONNECTÉ';$('game').textContent=state.running?'EN COURS':'ARRÊTÉ';$('branchBuild').textContent=state.running?state.branch+' '+short(state.build):'—';$('logState').textContent=state.logFound?'TROUVÉ':'ABSENT';$('footerStatus').textContent=state.running?state.branch+' · '+state.build+' · '+(state.shard||'shard en attente'):'STAR CITIZEN ARRÊTÉ';}
  function ctx(){return({UNKNOWN:'INCONNU',ON_FOOT:'À PIED',FLIGHT:'VOL',GROUND_VEHICLE:'VÉHICULE',MINING:'MINAGE',SALVAGE:'SALVAGE'})[state&&state.context]||'INCONNU';}
  function pages(){if(!state||!state.running||state.context==='UNKNOWN')return['Home','Settings'];if(state.context==='ON_FOOT')return['FPS','Settings'];return['Home','Combat','Systems','Settings'];}
  function nav(){const n=$('nav');n.replaceChildren();for(const p of pages()){const b=document.createElement('button');b.textContent={Home:'COCKPIT',Combat:'COMBAT',Systems:'SYSTÈMES',FPS:'À PIED',Settings:'RÉGLAGES'}[p];b.className=p===page?'active':'';b.onclick=()=>{page=p;render();};n.append(b);}}
  function head(title,sub){const h=document.createElement('div');h.className='page-head';const x=document.createElement('div');x.innerHTML='<div class="kicker">ASTERION / '+ctx()+'</div><h1>'+title+'</h1><p>'+sub+'</p>';const sw=document.createElement('div');sw.className='context-switch';[['AUTO','AUTO'],['ON_FOOT','À PIED'],['FLIGHT','VOL']].forEach(v=>{const b=document.createElement('button');b.textContent=v[1];b.onclick=()=>send('context',v[0]).catch(e=>toast(e.message));sw.append(b);});h.append(x,sw);return h;}
  function action(id,cls){let a=(state&&state.actions||[]).find(x=>x.id===id);if(!a)a={id:id,label:labels[id]||id,dangerous:id==='eject'||id==='destruct',bound:false,source:'NON LIÉ'};const b=document.createElement('button');b.className=cls+(a.dangerous?' danger':'');b.disabled=!connected||(!(state&&state.simulation)&&(!a.bound||!(state&&state.running)));const bind=(state&&state.simulation)?'SIM':a.bound?String(a.input||'').replace(/^kb1_/i,'').replaceAll('_',' ').toUpperCase():(a.source||'NON LIÉ');b.innerHTML='<span class="action-glyph">'+esc(glyph[id]||id.slice(0,3).toUpperCase())+'</span><b>'+esc(labels[id]||a.label)+'</b><small>'+(a.dangerous?'MAINTENIR · ':'')+esc(bind)+'</small>';if(a.dangerous){const p=document.createElement('span');p.className='progress';b.append(p);b.onpointerdown=e=>startHold(e,a,b,p);b.onpointerup=b.onpointercancel=b.onlostpointercapture=cancelHold;}else b.onclick=()=>execute(a,b);return b;}
  function panel(title,sub,ids,extra){const p=document.createElement('section');p.className='mfd-panel '+(extra||'');p.innerHTML='<div class="mfd-head"><b>'+title+'</b><span>'+sub+'</span></div>';const g=document.createElement('div');g.className='mfd-grid';ids.forEach(id=>g.append(action(id,'mfd-action')));p.append(g);return p;}
  function sessionBar(){const s=document.createElement('section');s.className='session-bar';[['VAISSEAU',state&&state.ship||'Non identifié'],['LOCALISATION',state&&state.location||'Indisponible'],['SHARD',state&&state.shard||'Indisponible'],['BUILD',state&&state.running?state.branch+' · '+short(state.build):'Hors ligne']].forEach(v=>{const d=document.createElement('div');d.innerHTML='<span>'+v[0]+'</span><b>'+esc(v[1])+'</b>';s.append(d);});return s;}
  function ship(c){c.append(head('MFD PRINCIPAL','Gros contrôles tactiles, organisés par fonction.'));const g=document.createElement('section');g.className='mfd-layout';g.append(panel('POWER','ÉNERGIE & DÉMARRAGE',['power','weapons','engines','shields','coolers','pw','pt','ps','balance'],'power-panel'),panel('FLIGHT','PILOTAGE',['master','brake','gear','vtol','landing','autoland','decoupled','cruise','gsafe','esp','limiter'],'flight-panel'),panel('SHIP SYSTEMS','SYSTÈMES',['mfd','mobiglas','starmap','camera','ping','scan','lights','headtrack','doors'],'systems-panel'),panel('TARGET','CIBLAGE & DÉFENSE',['lock','hostile','friendly','attacker','subtarget','pin','decoy','noise','missile','arm'],'target-panel'));const d=document.createElement('aside');d.className='danger-rail';d.append(action('eject','danger-tall'),action('destruct','danger-tall'));g.append(d);c.append(g);const sh=document.createElement('section');sh.className='shield-strip';const l=document.createElement('div');l.className='shield-label';l.innerHTML='<b>BOUCLIERS</b><span>Répartition · état réel non télémétré</span>';sh.append(l);['sf','sr','sl','sright','stop','sbottom','sreset'].forEach(id=>sh.append(action(id,'shield-action')));c.append(sh,sessionBar());}
  function foot(c){c.append(head('MODE À PIED','La disposition change automatiquement hors vaisseau.'));const g=document.createElement('section');g.className='foot-layout';g.append(panel('SUIT & VIEW','PERSONNEL',['mobiglas','flashlight','inventory','helmet','wipe','camera','starmap'],'foot-panel'),panel('ACTIONS','UTILITAIRES',['interact','heal','doors'],'foot-panel'),panel('EMOTES','SOCIAL',['salute','wave','respect'],'foot-panel'));const e=document.createElement('section');e.className='mfd-panel event-panel';e.innerHTML='<div class="mfd-head"><b>EVENT FEED</b><span>GAME.LOG</span></div>';const list=document.createElement('div');list.className='event-list';const ev=[...(state&&state.feed||[])].reverse().slice(0,8);if(!ev.length)list.innerHTML='<div class="empty">Aucun événement observé.</div>';else ev.forEach(x=>{const r=document.createElement('div');r.className='event-line';r.innerHTML='<time>'+esc(x.time||'--:--')+'</time><span>'+esc(x.text||'')+'</span>';list.append(r);});e.append(list);g.append(e);c.append(g,sessionBar());}
  function groups(c,title,data){c.append(head(title,'Commandes avancées regroupées sans doublons.'));const w=document.createElement('section');w.className='group-layout';Object.entries(data).forEach(([name,ids])=>w.append(panel(name,'COMMANDES',ids,'')));c.append(w);}
  function settings(c){c.append(head('PERSONNALISATION','Thèmes et couleurs du cockpit.'));const w=document.createElement('section');w.className='settings-grid';const themes=document.createElement('article');themes.className='setting-card';themes.innerHTML='<h3>PRÉSETS</h3><p>Choisissez une base visuelle.</p>';const tr=document.createElement('div');tr.className='preset-row';[['nebula','Nebula'],['graphite','Graphite'],['tactical','Tactical'],['minimal','Minimal']].forEach(v=>{const b=document.createElement('button');b.textContent=v[1];b.onclick=()=>send('theme',v[0]).catch(e=>toast(e.message));tr.append(b);});themes.append(tr);const colors=document.createElement('article');colors.className='setting-card';colors.innerHTML='<h3>COULEURS</h3><p>Accent, secondaire, fond et panneaux.</p>';const cg=document.createElement('div');cg.className='color-grid';[['accent','#24d9e8'],['accent2','#298cff'],['background','#040b11'],['panel','#0b1720']].forEach(v=>{const l=document.createElement('label');l.textContent=v[0];const i=document.createElement('input');i.type='color';i.value=state&&state.appearance&&state.appearance[v[0]]||v[1];i.onchange=()=>send(v[0],i.value).catch(e=>toast(e.message));l.append(i);cg.append(l);});colors.append(cg);const ver=document.createElement('article');ver.className='setting-card';ver.innerHTML='<h3>VERSION</h3><p>v'+VERSION+' · '+DEV+'</p>';w.append(themes,colors,ver);c.append(w);}
  function render(){nav();const c=$('content');c.replaceChildren();if(page==='Settings')settings(c);else if(page==='FPS')foot(c);else if(page==='Combat')groups(c,'COMBAT & CIBLAGE',{CIBLAGE:['lock','hostile','friendly','attacker','subtarget','pin'],ARMES:['weapons','missile','arm'],DÉFENSE:['decoy','noise'],CAPTEURS:['scan','ping']});else if(page==='Systems')groups(c,'SYSTÈMES DU VAISSEAU',{PILOTAGE:['brake','limiter','gsafe','esp','autoland','cruise','decoupled','master','gear','vtol','landing'],ÉNERGIE:['power','engines','weapons','shields','coolers','pw','pt','ps','balance'],BOUCLIERS:['sf','sr','sl','sright','stop','sbottom','sreset'],SYSTÈMES:['lights','doors','camera','headtrack','mfd','mobiglas','starmap','scan','ping','eject','destruct']});else ship(c);}
  function execute(a,b){send('action',a.id).then(()=>{toast((state&&state.simulation?'Simulation : ':'Commande envoyée : ')+(labels[a.id]||a.label));b.classList.add('sent');setTimeout(()=>b.classList.remove('sent'),250);}).catch(e=>toast(e.message));}
  function startHold(e,a,b,p){if(e.button!==0||b.disabled)return;e.preventDefault();cancelHold();const h={b:b,p:p,start:performance.now(),timer:null,raf:null};hold=h;send('holdBegin',a.id).then(()=>{h.start=performance.now();h.timer=setInterval(()=>raw({type:'holdPulse'}),150);const frame=()=>{if(hold!==h)return;const elapsed=performance.now()-h.start;p.style.width=Math.min(100,elapsed/(state&&state.holdDuration||1800)*100)+'%';if(elapsed>=(state&&state.holdDuration||1800)+80){clearInterval(h.timer);hold=null;p.style.width='0';execute(a,b);}else h.raf=requestAnimationFrame(frame);};h.raf=requestAnimationFrame(frame);}).catch(x=>toast(x.message));}
  function cancelHold(){if(!hold)return;clearInterval(hold.timer);cancelAnimationFrame(hold.raf);hold.p.style.width='0';hold=null;raw({type:'holdCancel'});}
  $('retryButton').onclick=()=>connect();window.addEventListener('blur',cancelHold);document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelHold();});setInterval(()=>{$('clock').textContent=new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'});},1000);render();connect();
})();